name: Example
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  windows:
    name: windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: run dart-cli example
        run: |
          cd ${{github.workspace}}\example\dart_cli
          dart --enable-experiment=native-assets run
      - name: run flutter example
        run: |
          cd ${{github.workspace}}\example\flutter
          flutter config --enable-native-assets
          flutter build windows --release
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: run dart-cli example
        run: |
          cd "${{github.workspace}}/example/dart_cli"
          dart --enable-experiment=native-assets run
      - name: run flutter example
        run: |
          cd "${{github.workspace}}/example/flutter"
          flutter config --enable-native-assets
          flutter build linux --release
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: run dart-cli example
        run: |
          cd "${{github.workspace}}/example/dart_cli"
          dart --enable-experiment=native-assets run
      - name: run flutter example
        run: |
          cd "${{github.workspace}}/example/flutter"
          flutter config --enable-native-assets
          flutter build macos --release
  ios:
    name: ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: flutter example
        run: |
          cd "${{github.workspace}}/example/flutter"
          flutter config --enable-native-assets
          flutter build ios --release --no-codesign
  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          add-to-path: true
      - name: flutter example
        run: |
          cd "${{github.workspace}}/example/flutter"
          flutter config --enable-native-assets
          flutter build apk --release
